// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPqIt0zoeTngPQ2G2q7P0Ih_SR4T240M',
    appId: '1:907330727936:web:9e180b702934f28f5868e5',
    messagingSenderId: '907330727936',
    projectId: 'chatapp-ae84d',
    authDomain: 'chatapp-ae84d.firebaseapp.com',
    storageBucket: 'chatapp-ae84d.appspot.com',
    measurementId: 'G-HEJ39R1HJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmXxG4ReKvSxb8Vx2RG7IAmHzFbX4giQ',
    appId: '1:907330727936:android:0f394e1f5b8a8cb45868e5',
    messagingSenderId: '907330727936',
    projectId: 'chatapp-ae84d',
    storageBucket: 'chatapp-ae84d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDueftYIsFlmmBVL-RjeMYCfqy4JqRlRH4',
    appId: '1:907330727936:ios:ce1a37f0b31357a65868e5',
    messagingSenderId: '907330727936',
    projectId: 'chatapp-ae84d',
    storageBucket: 'chatapp-ae84d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDueftYIsFlmmBVL-RjeMYCfqy4JqRlRH4',
    appId: '1:907330727936:ios:d0cbab76acc12e155868e5',
    messagingSenderId: '907330727936',
    projectId: 'chatapp-ae84d',
    storageBucket: 'chatapp-ae84d.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
